import datetime
#Dates in Python recap
#============================
print( )
print("dates in python...")
print('==========================')
x = datetime.datetime.now()
print(x)
print('--------------------------')
print( )
print("date output and date objects in python...")
print('==========================')
y = datetime.datetime(2019, 5, 17)
print(y.year)
print(y.month)
print(y.day)
print('--------------------------')
print( )
print("stringFormatting method time() in python...")
print('==========================')
z = datetime.datetime.now()
print(z.strftime("%B"))
print(z.strftime("%b"))
print(z.strftime("%A"))
print(z.strftime("%a"))
print(z.strftime("%x %X"))
print(z.strftime("%W"))
print('--------------------------')