#Functions in Python recap
#=========================
print( )
print("User Input in python")
print('==========================')
x = input('Write the first value')
print("x = input('Write the first value')")
print(x)
y = input("Write the second value, don't forget the space")
print("y = input('Write the second value')")
print(y)
print('For string concatenation:')
z = x + y
print('z = x + y')
print(z)
print('For using numbers:')
b = input('Write the third value, integer')
c = input('Write the fourth value, integer')
a = int(b) + int(c)
print('z = int(x) + int(y)')
print(a)
print('--------------------------')