#Operators in py recap
#===================
print( )
print("Types of operators in python")
print('==========================')

print('arythmetic operators...')
print('+')
print('-')
print('*')
print('/ , gives a float value')
print('// , gives an integer value')
print('% , gives the remainder after division , but still called percentage operator!')
x = 9 % 2
print('x = 9 % 2')
print('x = ')
print(x)
print('** , power operator')
print('--------------------------')
print('assignment operators...')
print('=')
print('+= , to increment value')
print('-= to decrement')
print('*=')
print('/= , gives a float value')
print('//== , gives an integer value')
print('%= , gives the remainder after division')
print('**= , power incrementor')
print('These are used a lot in loops.')
print('--------------------------')
print('comparison operators...')
print('==')
print('!=')
print('<')
print('<=')
print('>')
print('>=')
print('--------------------------')
print('logical operators...')
print('identity operators...')
print('membership operators (unique in python)...')
print('bitwise operators...')

print('--------------------------')