#Operators in py recap
#===================
print( )
print("Types of operators in python")
print('==========================')

print('arythmetic operators...')
print('+')
print('-')
print('*')
print('/ , gives a float value')
print('// , gives an integer value')
print('% , gives the remainder after division , but still called percentage operator!')
x = 9 % 2
print('x = 9 % 2')
print('x = ')
print(x)
print('** , power operator')
print('--------------------------')
print('assignment operators...')
print('=')
print('+= , to increment value')
print('-= to decrement')
print('*=')
print('/= , gives a float value')
print('//== , gives an integer value')
print('%= , gives the remainder after division')
print('**= , power incrementor')
print('These are used a lot in loops.')
print('--------------------------')
print('comparison operators...')
print('==')
print('!=')
print('<')
print('<=')
print('>')
print('>=')
print('--------------------------')
print('logical operators...')
print('and')
print('or')
print('not')
print('--------------------------')
print('identity operators...')
print('is')
print('is not')
print('--------------------------')
print('membership operators (unique in python)...')
x = "water is life"
print('in')
print('x = water is life')
print(x)
print(' "e" in x')
print('e' in x)
print('not in')
print('--------------------------')
print('bitwise operators...')
print('AND is written &')
print('OR is written |')
print('there is more, but at this point not relevant yet.')
print('--------------------------')